# Generated by Django 5.2.6 on 2026-06-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_dailyrecommendation_studyplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.TextField(blank=True, default=''),
        ),
    ]
